var annotated_dup =
[
    [ "AsteroidLogic", "class_asteroid_logic.html", "class_asteroid_logic" ],
    [ "AsteroidPresentation", "class_asteroid_presentation.html", "class_asteroid_presentation" ],
    [ "CollisionDetection", "class_collision_detection.html", "class_collision_detection" ],
    [ "EnemyBulletLogic", "class_enemy_bullet_logic.html", "class_enemy_bullet_logic" ],
    [ "EnemyBulletPresentation", "class_enemy_bullet_presentation.html", "class_enemy_bullet_presentation" ],
    [ "EnemyLogic", "class_enemy_logic.html", "class_enemy_logic" ],
    [ "EnemyPresentation", "class_enemy_presentation.html", "class_enemy_presentation" ],
    [ "FinalWindow", "class_final_window.html", "class_final_window" ],
    [ "GameLogic", "class_game_logic.html", "class_game_logic" ],
    [ "GamePresentation", "class_game_presentation.html", "class_game_presentation" ],
    [ "GameWindow", "class_game_window.html", "class_game_window" ],
    [ "IBullet", "class_i_bullet.html", "class_i_bullet" ],
    [ "IEnemy", "class_i_enemy.html", "class_i_enemy" ],
    [ "IMovingGameObject", "class_i_moving_game_object.html", "class_i_moving_game_object" ],
    [ "IntroductionWindow", "class_introduction_window.html", "class_introduction_window" ],
    [ "IPlayer", "class_i_player.html", "class_i_player" ],
    [ "LaserGeneratorLogic", "class_laser_generator_logic.html", "class_laser_generator_logic" ],
    [ "LaserGeneratorPresentation", "class_laser_generator_presentation.html", "class_laser_generator_presentation" ],
    [ "LifeLogic", "class_life_logic.html", "class_life_logic" ],
    [ "LifePresentation", "class_life_presentation.html", "class_life_presentation" ],
    [ "PlayerBullet", "class_player_bullet.html", "class_player_bullet" ],
    [ "PlayerBulletPresentation", "class_player_bullet_presentation.html", "class_player_bullet_presentation" ],
    [ "PlayerDetails", "struct_player_details.html", "struct_player_details" ],
    [ "PlayerLogic", "class_player_logic.html", "class_player_logic" ],
    [ "PlayerPresentation", "class_player_presentation.html", "class_player_presentation" ],
    [ "SatelliteLogic", "class_satellite_logic.html", "class_satellite_logic" ],
    [ "SatellitePresentation", "class_satellite_presentation.html", "class_satellite_presentation" ],
    [ "Score", "class_score.html", "class_score" ],
    [ "ScoreDatabase", "class_score_database.html", "class_score_database" ],
    [ "ScorePresentation", "class_score_presentation.html", "class_score_presentation" ]
];